### ISSUE TITLE
 [#REQ] Angular Material Table implementation: pagination, sorting, filtering...

### ISSUE THREAD

**Issue by josemorenoasix** [Ismaestro/angular9-example-app#38]
### Bug Report or Feature Request (mark with an `x`)

- [ ] bug report -> please search issues before submitting
- [x] feature request

### Desired functionality.

Implementation of an Angular Material table schematics with pagination, sort by column and name query filter from server and client side.
`$ ng generate @angular/material:table heroes-mat-table`

### Mention any other details that might be useful.

Nice job.
I am currently studying web development and I wanted to tell you that your project for me is very useful. It inspires me and teaches good practices. Thanks for share it.

**Comment by suprithasraoa** [comment]
Home Page ... Sort and Filter options would be of Great use! Please.. Thanks in advance
