### ISSUE TITLE
Demo app is SSR but repo isn't

### ISSUE THREAD

**Issue by aomerk** [Ismaestro/angular9-example-app#55]
Demo app is rendered on server and page source shows it too. It is not just
` <app-root>...spinner</app-root>` and kinda runs with JS disabled
But I cloned the repo, ran npm  install  and npm run deploy , deployed page is just a normal SPR.

**Comment by Ismaestro** [comment]
Be sure to refresh de view-source page because of the cache. Should be SSR, it makes no sense a SPA after deploying an ssr function among other things...

Can you confirm it?

**Comment by eliavmaman** [comment]
It's happens to me too
The local repo is not ssr:
1. clone the repo.
2. cd repo  and npm i.
3. npm run build:ssr.
4. npm run serve:ssr

pnavigate to localhost:4000 and view page source.
NOT SSR

**Comment by Ismaestro** [comment]
Did you reload the VIEW SOURCE page?

**Comment by eliavmaman** [comment]
Yes i did many times

**Comment by eliavmaman** [comment]
@Ismaestro i wrote you an email can u please have a look  ?

from eliavmaman2@gmail.com

**Comment by nicholas-davis** [comment]
Hello @eliavmaman, local is in SSR, but the deployed project to Firebase is not in SSR. Do you have any suggestions?

**Comment by nicholas-davis** [comment]
Hello @Ismaestro, first... great work! Love the setup. 

My issue is my local is in SSR, but the deployed project to Firebase is not in SSR. Do you have any suggestions? Any help is much much appreciated

**Comment by nicholas-davis** [comment]
Nevermind, SSR SEO is not working locally either. 

Did you ever get it to work @eliavmaman?

**Comment by nicholas-davis** [comment]
Nevermind, SSR SEO is not working locally either. 

Did you ever get it to work @eliavmaman @aomerk?

**Comment by nicholas-davis** [comment]
Fixed... it was a cache issue
