### ISSUE TITLE
Hero Details Page route is not working properly

### ISSUE THREAD

**Issue by simplecodeexamples** [Ismaestro/angular9-example-app#61]
**Describe the bug**
When hero details page is entered directly in the browser the page is breaking in multiple places.
Moreover javascript is not working in entire page

**To Reproduce**
1. run the project with npm run build:ssr and npm run serve:ssr
2. Copy and hero details page link by copy link address
3. Open that in a new tab
4. Now do a empty cache and hard reload
5. Page will break

**Expected behavior**
It should load the page just like when it is open from the home page. On performing hard reload in every page application should work as expected but in this page hard reload is breaking its layout and functionality

**Screenshots**
![image](https://user-images.githubusercontent.com/17008502/71067900-708a9800-219b-11ea-84b9-6c4b96020ac5.png)

**Desktop (please complete the following information):**
 - Browser :Chrome, Mozilla

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Ismaestro** [comment]
Has been fixed with the new v9.
