### ISSUE TITLE
Firebase deployed app not converting to SSR

### ISSUE THREAD

**Issue by nicholas-davis** [Ismaestro/angular9-example-app#65]
**Describe the bug**
Firebase deployed app in not converting to SSR on public website. 

Local works, but when I depoly the project via `firebase deploy`, the public website is not SEO friendly. I checked the view source, but no dice 

**Expected behavior**
public website view source should be in raw HTML, not angular rendered.

**Screenshots**

**Desktop (please complete the following information):**
mac

**Comment by nicholas-davis** [comment]
It appears the clone repo does not convert into a SEO friendly app

**Comment by Ismaestro** [comment]
The view source page is cached, be sure to fresh refresh the view-source page!!!
