### ISSUE TITLE
Angular 9 update

### ISSUE THREAD

**Issue by levonka** [Ismaestro/angular9-example-app#72]
Please upgrade the starter to angular 9

**Comment by Ismaestro** [comment]
Done!

**Comment by manzonif** [comment]
On server side, always is rendered the english locale. 

![Screenshot (41)](https://user-images.githubusercontent.com/8948699/82149081-7e317000-9856-11ea-8463-99cc21cff5f3.png)

**Comment by manzonif** [comment]
I'm working on this [solution](https://github.com/angular/universal/issues/1454#issuecomment-628131962), if can help...
